name: Log daily “Fresh!” count

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  archive_count:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch current count
        id: fetch
        run: |
          NAMESPACE='agentz-arts-archivals'
          DATE=$(date -I)
          KEY="trivia-yeah-$DATE"
          # call CountAPI and parse JSON
          COUNT=$(curl -s "https://api.countapi.xyz/get/$agentz-arts-archivals/$KEY" \
                   | jq -r '.value // 0')
          echo "::set-output name=date::$DATE"
          echo "::set-output name=count::$COUNT"

      - name: Append to log
        run: |
          echo "${{ steps.fetch.outputs.date }} : ${{ steps.fetch.outputs.count }}" \
            >> yeah.log

      - name: Commit and push archive
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add yeah.log
          git commit -m "Archive Yeah! count for ${{ steps.fetch.outputs.date }}" || echo "No changes to commit"
          git push
